default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: megs
  password: 0852369147

development:
  <<: *default
  database: RefurbCheck_development

test:
  <<: *default
  database: RefurbCheck_test

production:
  <<: *default
  database: RefurbCheck_production
